# Generated by Django 5.0.6 on 2024-06-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
